on: [push]

jobs:
  deploy_cloudify_job:
    runs-on: ubuntu-latest
    name: Deploy to Cloudify Job
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1
    - name: Install Openstack Client
      uses: BSFishy/pip-action@v1
      with:
        packages: python-openstackclient
    - name: Deploy Container to Cloudify
      uses: ./

      with: 
        credential_id: ${{ secrets.ID }}
        credential_secret: ${{ secrets.SECRET }}
        name: server-github-01
        keypair_name: test-key
        command: docker run --name wordpress-github -p 80:80 -d wordpress
